### PR TITLE
added new audio player settings: gsAudio

### PR DESCRIPTION
**Pull request by Tzyinc**
No change to calls to audioManager

workaround for issue #90

### CODE REVIEW

**Comment by ngzhian** [comment]
What's the reason for the duplicate player?

**Comment by Tzyinc** [comment]
The gSAudio mode allows you to play (the same) clips over each other, which means if you spam one sound over and over again there won't be the hiccup that you hear in the .aVAduioPlayer mode. you can switch mode in Config if you want to hear the difference

**Comment by anand-sundaram** [comment]
LGTM!

**Comment by ngzhian** [comment]
lgtm1

**Comment by advaypal** [comment]
@Tzyinc Can merge this?

**Pull request merged**
