### PR TITLE
Session name at the center of the top nav bar

### LINKED ISSUE #146: session name at the top of nav bar

### PR DESCRIPTION
**Pull request by ngzhian**
Fixes #146

### CODE REVIEW

**Comment by anand-sundaram** [comment]
@ngzhian When the name of the current session is changed, then the name on the Top Bar does not change, unless I reselect the changed session name in the session table. If I continue without reselecting the session in the session table, and then I save, then a new session with the old name gets created.

**Comment by ngzhian** [comment]
@anand-sundaram good catch! i have fixed this in the latest commit, PTAL!

**Comment by anand-sundaram** [comment]
Works fine, LGTM!

**Review by anand-sundaram — APPROVED** [review]
Works fine, LGTM!

**Pull request merged**
