### PR TITLE
Enabling relative animations

### PR DESCRIPTION
**Pull request by anand-sundaram**
@ngzhian `AnimationType` refers to the types of animations which will show up in the side bar. 

In this PR, I have
- Created a new enum `AnimationTypeCreationMode` with two values `.relative` and `.absolute`
- Created a new `AnimationManager` with a singleton instance which can be used to define new animation types
```
AnimationManager.instance.addNewAnimationType(name: String, animationSequence: AnimationSequence,
                             mode: AnimationTypeCreationMode, anchor: IndexPath)
```
- `AnimationSequence` for a given `AnimationType` and IndexPath of the clicked pad can be obtainted by calling
```
AnimationManager.instance.getAnimationSequenceForAnimationType(animationTypeName: String,
                                                     indexPath: IndexPath) -> AnimationSequence? 
```

@advaypal, you can serialize/deserialize `AnimationType` to JSON string by calling
- `animationType.getJSONforAnimationType() -> String?`
- `AnimationType.getAnimationTypeFromJSON(fromJSON: String) -> AnimationType?`

### CODE REVIEW

**Comment by anand-sundaram** [comment]
As of now, the `AnimationManager.instance.getAllAnimationTypesNames() -> [String]` serves the same purpose as `DataManager.instance.loadAllAnimations()`.

@ngzhian, is it better for the UI to retrieve all the animationTypes from DataManager directly, or through AnimationManager, since even the AnimationManager will need to keep track of all the animationTypes in order to be able to return the animationSequence for a selected animationType, and hence will need to access DataManager?

**Comment by ngzhian** [comment]
@anand-sundaram I think I will call animation manager to get all the animation type names :)

**Review by ngzhian — APPROVED** [review]
LGTM! Next PR maybe can write tests for the relativising code :)

**Comment by advaypal** [comment]
@ngzhian @anand-sundaram Sure, merge this in and I'll incorporate the changes into my PR

**Pull request merged**
