### PR TITLE
Design changes (animation designer + page selector)

### PR DESCRIPTION
**Pull request by ngzhian**
- Remove animation from animation table
- Remove sample from sample table
- refactor animation designer timeline (into view controller)
- refactor colour palette (into view controller)
- general clean up (magic constants, comments)
- use Colour.image instead of Colour.uiColor in palette
- new icons for page selector
- reimplemented nav bar
- session names can be edited (and saved)

screen shot 2017-04-06 at 1 12 09 am

### CODE REVIEW

**Comment by anand-sundaram** [comment]
@ngzhian it's a huge-ass PR so will take time to review and test. If this is blocking you, just go ahead and merge it..

**Comment by ngzhian** [comment]
Yea all the ui stuff kinda depended on one another, and in the interest of time i just kept pushing to the same branch sorry!
Will be good to pull and press around to make sure things still work, thanks!

**Comment by Tzyinc** [comment]
love the new page selector, created issues for my feedback (minor UI changes)

**Comment by ngzhian** [comment]
I will yolo and merge this in

**Pull request merged**
