### PR TITLE
Fix saving existing session

### PR DESCRIPTION
**Pull request by ngzhian**

### CODE REVIEW

**Comment by anand-sundaram** [comment]
LGTM for now (but we should remember to remove the force unwrap)

**Review by anand-sundaram — APPROVED** [review]
LGTM for now (but we should remember to remove the force unwrap later)

**Comment by ngzhian** [comment]
good reminder, i tried and this crashes for a new install, so I updated it to something safe. Please help me double check that it works for both new install and existing installs :) Thanks!

**Comment by anand-sundaram** [comment]
LGTM!

**Pull request merged**
